# Generated by Django 3.2.7 on 2023-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intensity', models.IntegerField()),
                ('Likehood', models.IntegerField()),
                ('Relevance', models.IntegerField()),
                ('Year', models.DateField()),
                ('Country', models.CharField(max_length=100)),
                ('Topic', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
            ],
        ),
    ]
