# Generated by Django 3.2.7 on 2023-06-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsLetter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='Year',
        ),
    ]
