# Generated by Django 3.2.7 on 2023-06-08 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsLetter', '0002_remove_dashboard_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='EYear',
            field=models.DateField(default=datetime.datetime(2023, 6, 8, 16, 37, 37, 583934)),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='SYear',
            field=models.DateField(default=datetime.datetime(2023, 6, 8, 16, 37, 37, 583934)),
        ),
    ]
