# Generated by Django 3.2.7 on 2023-06-08 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsLetter', '0003_auto_20230608_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='City',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='EYear',
            field=models.DateField(default=datetime.datetime(2023, 6, 8, 16, 45, 28, 210765)),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='SYear',
            field=models.DateField(default=datetime.datetime(2023, 6, 8, 16, 45, 28, 210765)),
        ),
    ]
