# Generated by Django 3.2.7 on 2023-06-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsLetter', '0004_auto_20230608_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='EYear',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='SYear',
            field=models.DateField(default=''),
        ),
    ]
