# Generated by Django 3.2.7 on 2023-06-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsLetter', '0007_auto_20230608_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='EYear',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='SYear',
            field=models.CharField(default='', max_length=100),
        ),
    ]
