# Generated by Django 3.2.7 on 2023-06-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsLetter', '0010_auto_20230608_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashBoard',
        ),
    ]
