# Generated by Django 3.2.7 on 2023-06-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NewsLetter', '0011_delete_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intensity', models.CharField(default='', max_length=100)),
                ('Likehood', models.CharField(default='', max_length=100)),
                ('Relevance', models.CharField(default='', max_length=100)),
                ('SYear', models.CharField(default='', max_length=100)),
                ('EYear', models.CharField(default='', max_length=100)),
                ('Country', models.CharField(default='', max_length=100)),
                ('Topic', models.CharField(default='', max_length=100)),
                ('Region', models.CharField(default='', max_length=100)),
                ('Url', models.CharField(default='', max_length=100)),
                ('Added', models.CharField(default='', max_length=100)),
                ('Published', models.CharField(default='', max_length=100)),
                ('Insight', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
